# Spring Boot Application Configuration
spring:
  application:
    name: fastlcdp

  # Internationalization Configuration
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: 3600

  # Data Source Configuration
  datasource:
    # Default H2 in-memory database for testing
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

    # MySQL Database Configuration Example (uncomment and modify connection info)
    # url: jdbc:mysql://localhost:3306/fastlcdp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # username: root
    # password: password

    # PostgreSQL Database Configuration Example (uncomment and modify connection info)
    # url: jdbc:postgresql://localhost:5432/fastlcdp
    # driver-class-name: org.postgresql.Driver
    # username: postgres
    # password: password

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none  # Do not auto-create tables, controlled by our framework
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # MySQL Dialect (uncomment when using MySQL)
        # dialect: org.hibernate.dialect.MySQL8Dialect
        # PostgreSQL Dialect (uncomment when using PostgreSQL)
        # dialect: org.hibernate.dialect.PostgreSQLDialect

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # H2 Console Configuration (for development and testing only)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: false

# SpringDoc Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: cn.com.traninfo.fastlcdp.controller
  paths-to-match: /api/**

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  # Undertow 优化配置
  undertow:
    # IO线程数，通常设置为CPU核心数
    io-threads: 4
    # 工作线程数，通常设置为IO线程数的8倍
    worker-threads: 32
    # 缓冲区大小
    buffer-size: 1024
    # 每个区域的缓冲区数量
    # 已弃用的配置，建议使用 server.undertow.buffer-pool-size 替代
    buffer-pool-size: 1024
    # 直接缓冲区
    direct-buffers: true
    # 访问日志
    accesslog:
      enabled: false
      dir: logs
      pattern: combined
      prefix: access_log
      suffix: .log

# Logging Configuration (使用log4j2)
logging:
  level:
    cn.com.traninfo.fastlcdp: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Management Endpoints Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Application Information
info:
  app:
    name: FastLCDP
    description: Spring Boot framework for generating database tables based on XML parsing
    version: 1.0.0