# Spring Boot Application Configuration
spring:
  application:
    name: fastlcdp

  # Data Source Configuration
  datasource:
    # Default H2 in-memory database for testing
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

    # MySQL Database Configuration Example (uncomment and modify connection info)
#     url: jdbc:mysql://localhost:3306/fastlcdp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     username: root
#     password: 1234

    # PostgreSQL Database Configuration Example (uncomment and modify connection info)
     url: jdbc:postgresql://localhost:5432/fastlcdp
     driver-class-name: org.postgresql.Driver
     username: postgres
     password: postgres

  # H2 Console Configuration (for development and testing only)
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#        trace: false

# SpringDoc Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: cn.com.traninfo.fastlcdp.controller
  paths-to-match: /api/**

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  # Undertow 优化配置
  undertow:
    # IO线程数，通常设置为CPU核心数
    io-threads: 4
    # 工作线程数，通常设置为IO线程数的8倍
    worker-threads: 32
    # 缓冲区大小
    buffer-size: 1024
    # 每个区域的缓冲区数量
    # 已弃用的配置，建议使用 server.undertow.buffer-pool-size 替代
    buffer-pool-size: 1024
    # 直接缓冲区
    direct-buffers: true

# Logging Configuration (使用log4j2)
logging:
  level:
    cn.com.traninfo.fastlcdp: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Database Configuration
database:
  type: POSTGRESQL  # 数据库类型: H2, MYSQL, POSTGRESQL, ORACLE, SQL_SERVER
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  enable-metadata-save: true
  metadata-table-prefix: xml_meta_
  auto-create-metadata-tables: true  # 启用自动建表功能

# MyBatis Plus Configuration
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: cn.com.traninfo.fastlcdp.entity

# Management Endpoints Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized