services:
  # FastLCDP应用服务
  fastlcdp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastlcdp-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ../logs:/app/logs
      - ../examples:/app/examples:ro
      - ../data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app_data:
    driver: local